import Logout from "@/components/Logout";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Energy Consumption(kwh)",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const cookiesList = cookies();
    const hasCookie = cookiesList.has("token");
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex justify-center mt-5">
                    <Logout cookie={hasCookie} />
                </div>
                {children}
            </body>
        </html>
    );
}
